FROM node:20-alpine

WORKDIR /app


RUN apk add --no-cache python3 py3-pip

COPY package.json package-lock.json ./

RUN npm install


COPY server.js .
COPY convert_embeddings.py .
COPY convert_gradcam.py .
COPY convert_attention.py .


COPY processed ./processed

EXPOSE 3000

CMD ["node", "server.js"]