CSS3_NAMES_RU = {
    # Базовые цвета
    'black': 'Чёрный',
    'silver': 'Серебристый',
    'gray': 'Серый',
    'white': 'Белый',
    'maroon': 'Бордовый',
    'red': 'Красный',
    'purple': 'Фиолетовый',
    'fuchsia': 'Фуксия',
    'green': 'Зелёный',
    'lime': 'Лаймовый',
    'olive': 'Оливковый',
    'yellow': 'Жёлтый',
    'navy': 'Тёмно-синий',
    'blue': 'Синий',
    'teal': 'Бирюзовый',
    'aqua': 'Аква',
    
    # Расширенные цвета
    'aliceblue': 'Бледно-голубой',
    'antiquewhite': 'Античный белый',
    'aquamarine': 'Аквамарин',
    'azure': 'Лазурный',
    'beige': 'Бежевый',
    'bisque': 'Бисквитный',
    'blanchedalmond': 'Миндальный',
    'blueviolet': 'Сине-фиолетовый',
    'brown': 'Коричневый',
    'burlywood': 'Светло-коричневый',
    'cadetblue': 'Серо-синий',
    'chartreuse': 'Шартрез',
    'chocolate': 'Шоколадный',
    'coral': 'Коралловый',
    'cornflowerblue': 'Васильковый',
    'cornsilk': 'Кукурузный',
    'crimson': 'Малиновый',
    'cyan': 'Циан',
    'darkblue': 'Тёмно-синий',
    'darkcyan': 'Тёмно-циановый',
    'darkgoldenrod': 'Тёмно-золотистый',
    'darkgray': 'Тёмно-серый',
    'darkgreen': 'Тёмно-зелёный',
    'darkgrey': 'Тёмно-серый',
    'darkkhaki': 'Тёмно-хаки',
    'darkmagenta': 'Тёмно-пурпурный',
    'darkolivegreen': 'Тёмно-оливковый',
    'darkorange': 'Тёмно-оранжевый',
    'darkorchid': 'Тёмно-лиловый',
    'darkred': 'Тёмно-красный',
    'darksalmon': 'Тёмно-лососевый',
    'darkseagreen': 'Тёмно-морской волны',
    'darkslateblue': 'Тёмно-грифельно-синий',
    'darkslategray': 'Тёмно-грифельно-серый',
    'darkslategrey': 'Тёмно-грифельно-серый',
    'darkturquoise': 'Тёмно-бирюзовый',
    'darkviolet': 'Тёмно-фиолетовый',
    'deeppink': 'Насыщенно-розовый',
    'deepskyblue': 'Насыщенный небесно-голубой',
    'dimgray': 'Тускло-серый',
    'dimgrey': 'Тускло-серый',
    'dodgerblue': 'Ярко-синий',
    'firebrick': 'Кирпичный',
    'floralwhite': 'Цветочно-белый',
    'forestgreen': 'Лесной зелёный',
    'gainsboro': 'Светло-серо-голубой',
    'ghostwhite': 'Призрачно-белый',
    'gold': 'Золотой',
    'goldenrod': 'Золотистый',
    'greenyellow': 'Зелёно-жёлтый',
    'grey': 'Серый',
    'honeydew': 'Медвяный',
    'hotpink': 'Ярко-розовый',
    'indianred': 'Индийский красный',
    'indigo': 'Индиго',
    'ivory': 'Слоновая кость',
    'khaki': 'Хаки',
    'lavender': 'Лавандовый',
    'lavenderblush': 'Розово-лавандовый',
    'lawngreen': 'Травяной зелёный',
    'lemonchiffon': 'Лимонно-шифоновый',
    'lightblue': 'Светло-голубой',
    'lightcoral': 'Светло-коралловый',
    'lightcyan': 'Светло-циановый',
    'lightgoldenrodyellow': 'Светло-золотисто-жёлтый',
    'lightgray': 'Светло-серый',
    'lightgreen': 'Светло-зелёный',
    'lightgrey': 'Светло-серый',
    'lightpink': 'Светло-розовый',
    'lightsalmon': 'Светло-лососевый',
    'lightseagreen': 'Светло-зелёно-морской',
    'lightskyblue': 'Светло-небесно-голубой',
    'lightslategray': 'Светло-грифельно-серый',
    'lightslategrey': 'Светло-грифельно-серый',
    'lightsteelblue': 'Светло-стальной синий',
    'lightyellow': 'Светло-жёлтый',
    'limegreen': 'Лимонно-зелёный',
    'linen': 'Льняной',
    'magenta': 'Пурпурный',
    'mediumaquamarine': 'Умеренный аквамарин',
    'mediumblue': 'Умеренный синий',
    'mediumorchid': 'Умеренный лиловый',
    'mediumpurple': 'Умеренный фиолетовый',
    'mediumseagreen': 'Умеренный морской волны',
    'mediumslateblue': 'Умеренный грифельно-синий',
    'mediumspringgreen': 'Умеренный весенне-зелёный',
    'mediumturquoise': 'Умеренный бирюзовый',
    'mediumvioletred': 'Умеренный фиолетово-красный',
    'midnightblue': 'Полночно-синий',
    'mintcream': 'Мятно-кремовый',
    'mistyrose': 'Туманно-розовый',
    'moccasin': 'Мокасиновый',
    'navajowhite': 'Навахо-белый',
    'oldlace': 'Старое кружево',
    'olivedrab': 'Тускло-оливковый',
    'orange': 'Оранжевый',
    'orangered': 'Оранжево-красный',
    'orchid': 'Орхидея',
    'palegoldenrod': 'Бледно-золотистый',
    'palegreen': 'Бледно-зелёный',
    'paleturquoise': 'Бледно-бирюзовый',
    'palevioletred': 'Бледно-фиолетово-красный',
    'papayawhip': 'Папайя',
    'peachpuff': 'Персиковый',
    'peru': 'Перу',
    'pink': 'Розовый',
    'plum': 'Сливовый',
    'powderblue': 'Пудрово-синий',
    'rosybrown': 'Розово-коричневый',
    'royalblue': 'Королевский синий',
    'saddlebrown': 'Кожано-коричневый',
    'salmon': 'Лососевый',
    'sandybrown': 'Песочно-коричневый',
    'seagreen': 'Морской волны',
    'seashell': 'Морская ракушка',
    'sienna': 'Сиена',
    'skyblue': 'Небесно-голубой',
    'slateblue': 'Грифельно-синий',
    'slategray': 'Грифельно-серый',
    'slategrey': 'Грифельно-серый',
    'snow': 'Снежный',
    'springgreen': 'Весенне-зелёный',
    'steelblue': 'Стальной синий',
    'tan': 'Жёлто-коричневый',
    'thistle': 'Чертополоховый',
    'tomato': 'Томатный',
    'turquoise': 'Бирюзовый',
    'violet': 'Фиолетовый',
    'wheat': 'Пшеничный',
    'whitesmoke': 'Дымчато-белый',
    'yellowgreen': 'Жёлто-зелёный',
    
    'rebeccapurple': 'Пурпурный Ребекки',
    'mediumvioletred': 'Умеренный фиолетово-красный',
    'darkturquoise': 'Тёмно-бирюзовый',
} 