FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1 # Не создавать .pyc файлы
ENV PYTHONUNBUFFERED 1     # Выводить логи Python сразу, без буферизации

WORKDIR /app

# Install necessary system libraries for OpenCV and other dependencies
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "api.py"] 